### ISSUE TITLE
Can't download the Trifo Ironsides dataset

### ISSUE THREAD

**Issue by izengpan** [TrifoRobotics/IRONSIDES#5]
Hello, I have read your great work Trifo-VIO, I think it's very interesting, and then I'd like to down load your Trifo Ironsides dataset to do some tests. But in the web page:
https://github.com/TrifoRobotics/IRONSIDES/wiki/Dataset
I can't open the down load links, nether the data nor the groundtruth. I have changed several browsers, and checked my network connections. But make no sense to the problem.

Thanks for you patient reply.

**Comment by zzhang001** [comment]
@izengpan We are working on migrating data to our new AWS data storage and we will let you know once it's done.

**Comment by izengpan** [comment]
Thanks for you quick reply again. So I guess that your migration work maybe won't be down in 1 week? Can you mke sure about this question?

**Comment by zzhang001** [comment]
The current link is still working. 
<img width="766" alt="screen shot 2018-11-09 at 10 06 16" src="https://user-images.githubusercontent.com/18743324/48238775-2b782c00-e407-11e8-83c7-a2963b985abd.png">

**Comment by izengpan** [comment]
Emmm, it works now.-_-||  
I don't know what had happend.
But thank you for your patient reply.

**Comment by kravinash** [comment]
Hi,

Very interesting work. 

But, the link to the dataset doesn't seem to work. 

Thanks,

**Comment by fzheng010** [comment]
@kravinash Thanks for your interest. We have just updated the links and verified that they are working.

**Comment by kravinash** [comment]
Great..it is working now

Thanks
