### ISSUE TITLE
Format of robot_pose.csv

### ISSUE THREAD

**Issue by siddhya** [TrifoRobotics/IRONSIDES#6]
What are the column labels and descriptions in the ground truth file on the dataset? Thanks.

**Comment by fzheng010** [comment]
timestamp tx ty tz qx qy qz qw
You could use TUM's benchmark scripts to do evaluation: https://vision.in.tum.de/data/datasets/rgbd-dataset/tools

**Comment by fzheng010** [comment]
The dataset wiki page has been updated. Thanks for raising the question.
Closing the issue.
